# Generated by Django 3.1 on 2020-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='login')),
                ('passw', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
