# Generated by Django 3.1 on 2020-09-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='code',
            new_name='token',
        ),
    ]
