# Generated by Django 3.1 on 2020-09-30 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0004_auto_20200930_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('timecreate', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('timeupdate', models.DateTimeField(auto_now=True, verbose_name='время последнего изменения')),
                ('status', models.PositiveIntegerField(verbose_name='статус')),
                ('timeplane', models.DateTimeField(verbose_name='планируемое время завершения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
