# Generated by Django 3.1 on 2020-09-30 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuidtask',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='уникальный идентификатор'),
        ),
    ]
