# Generated by Django 3.1 on 2020-09-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_task_uuidtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryChangeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('timecreate', models.DateTimeField(auto_now_add=True, verbose_name='время создания истороии')),
                ('status', models.PositiveIntegerField(verbose_name='статус')),
                ('timeplane', models.DateTimeField(verbose_name='планируемое время завершения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='apiapp.task')),
            ],
        ),
    ]
